CREATE TABLE simple_ledger_chart_of_accounts (
    id INT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    normal_balance VARCHAR(10) NOT NULL,
    description TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (id),
    UNIQUE KEY simple_ledger_chart_of_accounts_code_key (code)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE simple_ledger_transactions (
    id INT NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    description TEXT NULL,
    is_correction TINYINT(1) NOT NULL DEFAULT 0,
    corrected_from_id INT NULL,
    correction_note TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (id),
    KEY simple_ledger_transactions_date_created_idx (date DESC, created_at DESC),
    KEY simple_ledger_transactions_corrected_from_id_idx (corrected_from_id),
    CONSTRAINT simple_ledger_transactions_corrected_from_id_fkey
        FOREIGN KEY (corrected_from_id) REFERENCES simple_ledger_transactions (id)
        ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE simple_ledger_journal_entries (
    id INT NOT NULL AUTO_INCREMENT,
    transaction_id INT NOT NULL,
    chart_of_accounts_id INT NOT NULL,
    type VARCHAR(10) NOT NULL,
    amount INT NOT NULL,
    description TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    PRIMARY KEY (id),
    KEY simple_ledger_journal_entries_transaction_id_idx (transaction_id),
    KEY simple_ledger_journal_entries_chart_of_accounts_id_idx (chart_of_accounts_id),
    CONSTRAINT simple_ledger_journal_entries_transaction_id_fkey
        FOREIGN KEY (transaction_id) REFERENCES simple_ledger_transactions (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT simple_ledger_journal_entries_chart_of_accounts_id_fkey
        FOREIGN KEY (chart_of_accounts_id) REFERENCES simple_ledger_chart_of_accounts (id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 勘定科目マスタ（元アプリの chart_of_accounts_seed.go を移植）
INSERT INTO simple_ledger_chart_of_accounts (code, name, type, normal_balance, description) VALUES
    ('1000', '現金', 'asset', 'debit', '現金及び小切手'),
    ('1010', '普通預金', 'asset', 'debit', '銀行の普通預金口座'),
    ('1020', '定期預金', 'asset', 'debit', '銀行の定期預金'),
    ('1100', '売上債権', 'asset', 'debit', '売掛金及び受取手形'),
    ('1110', '売掛金', 'asset', 'debit', '商品売上に対する掛け売りの請求権'),
    ('1200', '商品', 'asset', 'debit', '販売目的の商品在庫'),
    ('1300', '建物', 'asset', 'debit', '事業用の建物'),
    ('1310', '建物減価償却累計額', 'asset', 'credit', '建物の減価償却累計額'),
    ('1400', '機械装置', 'asset', 'debit', '製造設備や事務機器'),
    ('1410', '機械装置減価償却累計額', 'asset', 'credit', '機械装置の減価償却累計額'),
    ('1500', '車両', 'asset', 'debit', '事業用の車両'),
    ('1510', '車両減価償却累計額', 'asset', 'credit', '車両の減価償却累計額'),
    ('2000', '買掛金', 'liability', 'credit', '商品購入時の掛け買いの支払い義務'),
    ('2100', '支払手形', 'liability', 'credit', '掛け買いで振り出した手形'),
    ('2200', '短期借入金', 'liability', 'credit', '1年以内に返済予定の借金'),
    ('2300', '長期借入金', 'liability', 'credit', '1年を超える返済予定の借金'),
    ('2400', '給料引当金', 'liability', 'credit', '未払い給料の見積もり'),
    ('3000', '資本金', 'equity', 'credit', '事業開始時の投資資本'),
    ('3100', '利益剰余金', 'equity', 'credit', '過去年度の利益の蓄積'),
    ('3200', '当期利益', 'equity', 'credit', '当年度の利益'),
    ('4000', '売上', 'revenue', 'credit', '商品やサービスの売上'),
    ('4100', '売上返品', 'revenue', 'debit', '売上の返品・キャンセル'),
    ('4200', '売上割引', 'revenue', 'debit', '売上時の割引'),
    ('4300', '受取利息', 'revenue', 'credit', '銀行利息や貸付金の利息'),
    ('4400', '雑収入', 'revenue', 'credit', 'その他の収入'),
    ('5000', '仕入', 'expense', 'debit', '販売目的の商品仕入'),
    ('5100', '仕入返品', 'expense', 'credit', '仕入の返品・キャンセル'),
    ('5200', '仕入割引', 'expense', 'credit', '仕入時の割引'),
    ('6000', '給料', 'expense', 'debit', '従業員の給料'),
    ('6100', '福利厚生費', 'expense', 'debit', '健康保険や厚生年金などの福利厚生'),
    ('6200', '社会保険料', 'expense', 'debit', '企業負担分の社会保険料'),
    ('6300', '賃借料', 'expense', 'debit', 'オフィスやテナントの賃料'),
    ('6400', '水道光熱費', 'expense', 'debit', '電気、ガス、水道などの費用'),
    ('6500', '通信費', 'expense', 'debit', '電話やインターネットの費用'),
    ('6600', '減価償却費', 'expense', 'debit', '固定資産の減価償却費'),
    ('6700', '旅費交通費', 'expense', 'debit', '移動や出張の費用'),
    ('6800', '消耗品費', 'expense', 'debit', 'オフィス消耗品などの費用'),
    ('6900', '修繕費', 'expense', 'debit', '建物や設備の修繕費'),
    ('7000', '支払利息', 'expense', 'debit', '借入金の利息'),
    ('7100', '雑費', 'expense', 'debit', 'その他の費用');

-- サンプル取引（デモ用。実行日からの相対日付で常に「直近」のデータに見えるようにする）
INSERT INTO simple_ledger_transactions (id, date, description) VALUES
    (1, DATE_SUB(CURDATE(), INTERVAL 60 DAY), '業務委託報酬の入金'),
    (2, DATE_SUB(CURDATE(), INTERVAL 58 DAY), '家賃の支払い'),
    (3, DATE_SUB(CURDATE(), INTERVAL 56 DAY), '電気・ガス・水道代の支払い'),
    (4, DATE_SUB(CURDATE(), INTERVAL 55 DAY), '携帯電話・インターネット料金の支払い'),
    (5, DATE_SUB(CURDATE(), INTERVAL 50 DAY), '食料品・日用品の購入'),
    (6, DATE_SUB(CURDATE(), INTERVAL 45 DAY), 'フリマアプリでの売却'),
    (7, DATE_SUB(CURDATE(), INTERVAL 42 DAY), '電車・バス運賃の支払い'),
    (8, DATE_SUB(CURDATE(), INTERVAL 38 DAY), '普通預金の利息'),
    (9, DATE_SUB(CURDATE(), INTERVAL 30 DAY), '業務委託報酬の入金'),
    (10, DATE_SUB(CURDATE(), INTERVAL 28 DAY), '家賃の支払い'),
    (11, DATE_SUB(CURDATE(), INTERVAL 25 DAY), '電気・ガス・水道代の支払い'),
    (12, DATE_SUB(CURDATE(), INTERVAL 24 DAY), '携帯電話・インターネット料金の支払い'),
    (13, DATE_SUB(CURDATE(), INTERVAL 20 DAY), '食料品・日用品の購入'),
    (14, DATE_SUB(CURDATE(), INTERVAL 18 DAY), '電車・バス運賃の支払い'),
    (15, DATE_SUB(CURDATE(), INTERVAL 15 DAY), '食料品の購入'),
    (16, DATE_SUB(CURDATE(), INTERVAL 14 DAY), '現金を口座に預け入れ'),
    (17, DATE_SUB(CURDATE(), INTERVAL 12 DAY), '自転車の修理'),
    (18, DATE_SUB(CURDATE(), INTERVAL 10 DAY), '週末の外出交通費'),
    (19, DATE_SUB(CURDATE(), INTERVAL 8 DAY), '食料品の購入'),
    (20, DATE_SUB(CURDATE(), INTERVAL 7 DAY), 'ジムの利用料'),
    (21, DATE_SUB(CURDATE(), INTERVAL 5 DAY), 'その他の細かい支出'),
    (22, DATE_SUB(CURDATE(), INTERVAL 3 DAY), '業務委託報酬の入金'),
    (23, DATE_SUB(CURDATE(), INTERVAL 2 DAY), '食料品の購入');

INSERT INTO simple_ledger_journal_entries (transaction_id, chart_of_accounts_id, type, amount, description) VALUES
    (1, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'debit', 250000, '普通預金への入金'),
    (1, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '4000'), 'credit', 250000, '業務委託報酬'),
    (2, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6300'), 'debit', 85000, '家賃'),
    (2, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 85000, '普通預金からの引き落とし'),
    (3, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6400'), 'debit', 10500, '電気・ガス・水道代'),
    (3, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 10500, '普通預金からの引き落とし'),
    (4, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6500'), 'debit', 8500, '携帯電話・インターネット料金'),
    (4, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 8500, '普通預金からの引き落とし'),
    (5, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6800'), 'debit', 6400, '食料品・日用品'),
    (5, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 6400, '現金払い'),
    (6, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'debit', 5000, 'フリマアプリの売上金'),
    (6, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '4400'), 'credit', 5000, '不用品の売却'),
    (7, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6700'), 'debit', 4200, '電車・バス運賃'),
    (7, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 4200, '現金払い'),
    (8, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'debit', 3000, '利息の入金'),
    (8, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '4300'), 'credit', 3000, '普通預金の利息'),
    (9, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'debit', 250000, '普通預金への入金'),
    (9, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '4000'), 'credit', 250000, '業務委託報酬'),
    (10, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6300'), 'debit', 85000, '家賃'),
    (10, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 85000, '普通預金からの引き落とし'),
    (11, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6400'), 'debit', 12000, '電気・ガス・水道代'),
    (11, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 12000, '普通預金からの引き落とし'),
    (12, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6500'), 'debit', 8500, '携帯電話・インターネット料金'),
    (12, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 8500, '普通預金からの引き落とし'),
    (13, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6800'), 'debit', 5800, '食料品・日用品'),
    (13, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 5800, '現金払い'),
    (14, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6700'), 'debit', 3600, '電車・バス運賃'),
    (14, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 3600, '現金払い'),
    (15, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6800'), 'debit', 3800, '食料品'),
    (15, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 3800, '現金払い'),
    (16, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'debit', 20000, '普通預金口座への入金'),
    (16, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 20000, '現金からの預け入れ'),
    (17, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6900'), 'debit', 15000, '自転車の修理費'),
    (17, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 15000, '普通預金からの引き落とし'),
    (18, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6700'), 'debit', 9800, '週末の外出交通費'),
    (18, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 9800, '現金払い'),
    (19, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6800'), 'debit', 5200, '食料品'),
    (19, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 5200, '現金払い'),
    (20, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6100'), 'debit', 8000, 'ジムの月会費'),
    (20, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'credit', 8000, '普通預金からの引き落とし'),
    (21, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '7100'), 'debit', 1500, 'その他の細かい支出'),
    (21, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 1500, '現金払い'),
    (22, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1010'), 'debit', 250000, '普通預金への入金'),
    (22, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '4000'), 'credit', 250000, '業務委託報酬'),
    (23, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '6800'), 'debit', 4600, '食料品'),
    (23, (SELECT id FROM simple_ledger_chart_of_accounts WHERE code = '1000'), 'credit', 4600, '現金払い');
